server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: pms-route
          uri: lb://user-service
          predicates:
            - Path=/admin/user/**
